source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'MBProgressHUD', '~> 0.9.1'
pod 'pop', '~> 1.0'
pod 'SDWebImage', '~> 3.7'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'CRToast', '~> 0.0.7'
pod 'CMPopTipView', '~> 2.2'
pod 'DateTools'
pod 'KLCPopup', '~> 1.0'
pod 'HCSStarRatingView', '~> 1.2'
pod 'ActionSheetPicker-3.0'
pod 'QRCodeReaderViewController', '~> 3.5.2'
pod 'AVOSCloud'
pod "Appirater"