source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'Valet'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'pop', '~> 1.0'
pod 'Mantle', '~> 2.0'
pod 'SDWebImage', '~> 3.7'
pod 'SDCycleScrollView','~> 1.3'
pod 'AVOSCloud'