source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'SVProgressHUD'
pod 'SDWebImage', '~> 3.7'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'DateTools'
pod "Appirater"
pod 'Fabric'
pod 'Crashlytics'
pod 'Instabug'
pod 'UMengAnalytics-NO-IDFA'
pod 'AFNetworking', '~> 2.6.1'
pod 'SSKeychain'
pod 'MJRefresh'
pod 'Masonry'
pod 'Mantle'
pod 'CRToast'
pod 'KLCPopup'
pod 'pop', '~> 1.0'
pod 'StepSlider'
pod 'BEMCheckBox'